---
title: "Contributor Code of Conduct"
author: "Project Team"
date: '2024-02-15'
output: html_document
---

### Contributor Code of Conduct

As contributors and maintainers of this project, and in the interest of fostering an open and welcoming environment, we pledge to respect all individuals who contribute through various means such as reporting issues, posting feature requests, updating documentation, submitting pull requests or patches, and other activities related to the development and enhancement of the project.

We are committed to making participation in this project a harassment-free experience for everyone, regardless of their level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, religion, or nationality.

**Examples of unacceptable behavior by participants include:**

- The use of sexualized language or imagery.
- Personal attacks.
- Trolling or insulting/derogatory comments.
- Public or private harassment.
- Publishing others' private information, such as physical or electronic addresses, without explicit permission.
- Other unethical or unprofessional conduct.

Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned with this Code of Conduct. They can also ban temporarily or permanently any contributor for behaviors they deem inappropriate, threatening, offensive, or harmful.

By adopting this Code of Conduct, project maintainers commit themselves to fairly and consistently applying these principles to every aspect of managing this project. Project maintainers who do not follow or enforce the Code of Conduct may be permanently removed from the project team.

This Code of Conduct applies both within project spaces and in public spaces when an individual is representing the project or its community.

Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting a designated working group via email (18rt20@queensu.ca). This email address will be accessible to the working group members only, ensuring confidentiality. The working group is committed to promptly addressing any reported issues, with the current members including:

- Hanwen Zhang
- Zerui Zhang
- Shiyi Chen
- Marina Tian

All complaints will be reviewed and investigated and will result in a response deemed necessary and appropriate to the circumstances. Maintainers are obligated to maintain confidentiality with regard to the reporter of an incident.

This Code of Conduct is adapted from the Contributor Covenant, version 1.3.0, available at [http://contributor-covenant.org/version/1/3/0/](http://contributor-covenant.org/version/1/3/0/), and influenced by the Swift Code of Conduct.
